Description of config
Home > simulation > config.m
config
PURPOSE
CONFIG Returns configuration values.
SYNOPSIS
function dbConnectionParameters = config()
DESCRIPTION
CONFIG Returns configuration values.
 Author: Jonathan Karr, jkarr@stanford.edu
 Affilitation: Covert Lab, Department of Bioengineering, Stanford University
 Last updated: 9/21/2010
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generateTestFixtures Generates test fixtures for whole cell simulation.
loadSimulation Load whole cell simulation from disk/database.
runSimulation Executes whole cell simulation.
SOURCE CODE
function dbConnectionParameters = config()
%CONFIG Returns configuration values.
%
% Author: Jonathan Karr, jkarr@stanford.edu
% Affilitation: Covert Lab, Department of Bioengineering, Stanford University
% Last updated: 9/21/2010
%% knowledgebase
dbConnectionParameters.hostName = 'covertlab.stanford.edu';
dbConnectionParameters.schema   = 'wholecell';
dbConnectionParameters.userName = 'wholecell';
dbConnectionParameters.password = 'wholecell';