Description of runReindexing
Home > simulation > runReindexing.m
runReindexing
PURPOSE
Reindexes whole cell simulation.
SYNOPSIS
function runReindexing(outputDirectory)
DESCRIPTION
 Reindexes whole cell simulation.
 Author: Jonathan Karr, jkarr@stanford.edu
 Affilitation: Covert Lab, Department of Bioengineering, Stanford University
 Last updated: 6/30/2011
CROSS-REFERENCE INFORMATION
This function calls:
setPath SETPATH Adds folders to MATLAB path and MATLAB Java path.
setPreferences SETPREFERENCES Sets MATLAB preferences
setWarnings SETWARNINGS Turns on and off (mostly off) specific warnings.
This function is called by:
SOURCE CODE
% Reindexes whole cell simulation.
%
% Author: Jonathan Karr, jkarr@stanford.edu
% Affilitation: Covert Lab, Department of Bioengineering, Stanford University
% Last updated: 6/30/2011
function runReindexing(outputDirectory)
setWarnings();
setPath();
setPreferences();
import edu.stanford.covert.cell.sim.util.DiskLogger;
DiskLogger.reindexTimeCourses(outputDirectory);