Description of runSimulation
Home > simulation > runSimulation.m
runSimulation
PURPOSE
Executes whole cell simulation.
SYNOPSIS
function simulation = runSimulation(configDirectory, logToDisk, logToDatabase)
DESCRIPTION
 Executes whole cell simulation.
 Author: Jonathan Karr, jkarr@stanford.edu
 Author: Jared Jacobs, jmjacobs@stanford.edu
 Affilitation: Covert Lab, Department of Bioengineering, Stanford University
 Last updated: 1/9/2011
% initialize
CROSS-REFERENCE INFORMATION
This function calls:
config CONFIG Returns configuration values.
setPath SETPATH Adds folders to MATLAB path and MATLAB Java path.
setPreferences SETPREFERENCES Sets MATLAB preferences
setWarnings SETWARNINGS Turns on and off (mostly off) specific warnings.
This function is called by:
SOURCE CODE
% Executes whole cell simulation.
%
% Author: Jonathan Karr, jkarr@stanford.edu
% Author: Jared Jacobs, jmjacobs@stanford.edu
% Affilitation: Covert Lab, Department of Bioengineering, Stanford University
% Last updated: 1/9/2011
function simulation = runSimulation(configDirectory, logToDisk, logToDatabase)
%% initialize
setWarnings();
setPath();
setPreferences();
%% import
import edu.stanford.covert.cell.sim.constant.Condition;
import edu.stanford.covert.cell.sim.util.ConditionSet;
import edu.stanford.covert.cell.sim.util.DatabaseLogger;
import edu.stanford.covert.cell.sim.util.DiskLogger;
import edu.stanford.covert.cell.sim.util.SummaryLogger;
import edu.stanford.covert.db.MySQLDatabase;
%% load simulation object
load('data/Simulation_fitted.mat');
%% process options, setup loggers
summaryLogger = SummaryLogger(1, 2);
loggers = {summaryLogger};
if nargin >= 1
    if ~exist([configDirectory filesep 'conditions.xml'], 'file')
        throw(MException('runSimulation:error', 'Directory must contain a condition xml file: %s', [configDirectory filesep 'conditions.xml']));
    end
    data = ConditionSet.parseConditionSet(simulation, [configDirectory filesep 'conditions.xml']);
    data.metadata.knowledgeBaseWID = knowledgeBaseWID;
    simulation.applyOptions(data.options);
    simulation.applyOptions(data.perturbations);
    simulation.applyParameters(data.parameters);
    summaryLogger.setOptions(struct('verbosity', simulation.verbosity, 'outputDirectory', configDirectory));
end
if nargin >= 2 && ((ischar(logToDisk) && strcmp(logToDisk, 'true')) || logToDisk)
    diskLogger = DiskLogger(configDirectory, 100);
    diskLogger.addMetadata(data.metadata);
    loggers = [loggers; {diskLogger}];
end
if nargin >= 3 && ((ischar(logToDatabase) && strcmp(logToDatabase, 'true')) || logToDatabase)
    databaseLogger = DatabaseLogger(MySQLDatabase(config), 1000);
    databaseLogger.addMetadata(data.metadata);
    loggers = [loggers; {databaseLogger}];
end
%% simulate
try
    simulation.run(loggers);
catch exception
    if nargin == 0
        errFile = ['tmp' filesep 'simulation_error_' datestr(now, 'yyyy_mm_dd_HH_MM_SS_FFF') '.mat'];
    else
        errFile = [configDirectory filesep 'err.mat'];
    end
    try
        save(errFile, 'simulation');
    catch saveException
        exception.addCause(MException('Simulation:runTimeError', ...
            'Simulation run-time error at %d. Unable to save simulation and exiting.', ...
            simulation.state('Time').values)).addCause(saveException).rethrow();
    end
    exception.addCause(MException('Simulation:runTimeError', ...
        'Simulation run-time error at %d. Saving simulation at ''%s'' and exiting.', ...
        simulation.state('Time').values, errFile)).rethrow();
end