Description of setPreferences
Home > simulation > setPreferences.m
setPreferences
PURPOSE
SETPREFERENCES Sets MATLAB preferences
SYNOPSIS
function setPreferences()
DESCRIPTION
SETPREFERENCES Sets MATLAB preferences
 Author: Jonathan Karr, jkarr@stanford.edu
 Author: Derek Macklin, macklin@stanford.edu
 Affilitation: Covert Lab, Department of Bioengineering, Stanford University
 Last updated: 9/6/2011
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generateTestFixtures Generates test fixtures for whole cell simulation.
loadSimulation Load whole cell simulation from disk/database.
runAnalysis Analyzes whole cell simulations.
runAnalysisTests Runs the analysis tests for the whole cell simulation.
runAnimation Generates an animation
runChromosomeTests Run chromosome tests.
runCoverageTests Gathers code coverage for whole cell simulation tests.
runLargeTests Runs the large tests for the whole cell simulation.
runMediumDNATests Runs the medium DNA tests for the whole cell simulation.
runMediumProteinTests Runs the medium protein tests for the whole cell simulation.
runMediumTests Runs the medium tests for the whole cell simulation.
runReindexing Reindexes whole cell simulation.
runSimulation Executes whole cell simulation.
runSimulationTests Runs a full length simulation.
runSmallTests Runs the small tests for the whole cell simulation.
SOURCE CODE
function setPreferences()
%SETPREFERENCES Sets MATLAB preferences
%
% Author: Jonathan Karr, jkarr@stanford.edu
% Author: Derek Macklin, macklin@stanford.edu
% Affilitation: Covert Lab, Department of Bioengineering, Stanford University
% Last updated: 9/6/2011
%prevent MATLAB from using OpenGL to avoid segmentation faults
set(0, 'DefaultFigureRenderer', 'painters')
opengl('neverselect')
%set character encoding to UTF-8
if ~isdeployed
    slCharacterEncoding('UTF-8');
end
%default font
set(0, 'defaultAxesFontName', 'Arial')
set(0, 'defaultTextFontName', 'Arial')