Description of setWarnings
Home > simulation > setWarnings.m
setWarnings
PURPOSE
SETWARNINGS Turns on and off (mostly off) specific warnings.
SYNOPSIS
function setWarnings()
DESCRIPTION
SETWARNINGS Turns on and off (mostly off) specific warnings.
 Author: Jonathan Karr, jkarr@stanford.edu
 Affilitation: Covert Lab, Department of Bioengineering, Stanford University
 Last updated: 9/21/2010
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generateTestFixtures Generates test fixtures for whole cell simulation.
install Installs whole-cell model
loadSimulation Load whole cell simulation from disk/database.
runAnalysis Analyzes whole cell simulations.
runAnalysisTests Runs the analysis tests for the whole cell simulation.
runAnimation Generates an animation
runChromosomeTests Run chromosome tests.
runCoverageTests Gathers code coverage for whole cell simulation tests.
runDisplacementCalculation Calculates DNA-bound protein displacements
runLargeTests Runs the large tests for the whole cell simulation.
runMediumDNATests Runs the medium DNA tests for the whole cell simulation.
runMediumProteinTests Runs the medium protein tests for the whole cell simulation.
runMediumTests Runs the medium tests for the whole cell simulation.
runReindexing Reindexes whole cell simulation.
runSimulation Executes whole cell simulation.
runSimulationTests Runs a full length simulation.
runSmallTests Runs the small tests for the whole cell simulation.
SOURCE CODE
function setWarnings()
%SETWARNINGS Turns on and off (mostly off) specific warnings.
%
% Author: Jonathan Karr, jkarr@stanford.edu
% Affilitation: Covert Lab, Department of Bioengineering, Stanford University
% Last updated: 9/21/2010
warning('off', 'MATLAB:dispatcher:nameConflict');
warning('off', 'MATLAB:class:cannotUpdateClass');
warning('off', 'MATLAB:ClassInstanceExists');
warning('off', 'MATLAB:xlsread:Mode')
warning('off', 'MATLAB:xlsread:RangeIncompatible');
warning('off', 'MATLAB:javaclasspath:duplicateEntry');
warning('off', 'MATLAB:xlswrite:AddSheet');
warning('off', 'MATLAB:structOnObject');
warning('off', 'MATLAB:Print:CustomResizeFcnInPrint');
warning('off', 'MATLAB:save:sizeTooBigForMATFile');
warning('off', 'MATLAB:load:variableNotFound');
warning('off', 'WholeCell:warning:network');
warning('off', 'WholeCell:warning:initializeNegativeCounts');
warning('off', 'MATLAB:Axes:NegativeDataInLogAxis');
warning('off', 'swtest:largeSampleSize');
warning('off', 'stats:gamfit:ZerosInData');